// Packet.js
// Defines what a "packet" looks like in MongoDB

import mongoose from 'mongoose'; 

// blueprint for what a packet looks like in the database
const packetSchema = new mongoose.Schema(
    {
        // packetId is a unique identifier for each packet, generated by the client
        packetId: { type: String, required: true },

        // flowId is a unique identifier for the flow that this packet belongs to, generated by the client
        flowId: { type: String, required: true },

        // sourceNode and destNode are the IP addresses of the source and destination of the packet
        sourceNode: { type: String, required: true },
        destNode: { type: String, required: true },

        // sourceRole and destRole are the roles of the source and destination of the packet (e.g. "client", "server", "router", etc.)
        sourceRole: { type: String, required: true },
        destRole: { type: String, required: true },

        // protocol is the protocol of the packet (e.g. "TCP", "UDP", etc.)
        payload: { type: String, required: true },

        // rateHz is the rate of the packet in Hz, calculated by the client
        rateHz: { type: Number, required: true },

        // timestamp is the time that the packet was captured, generated by the client
        timestamp: { type: Date, required: true }
    },
    { timestamps: true }
);

// used to prevent duplicate packets from being stored in the database
packetSchema.index({ packetId: 1 }, { unique: true });

const Packet = mongoose.model('Packet', packetSchema);   

export default Packet;